version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: stagecompanion-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=stagedb
        - MYSQL_USER=stageApi
        - MYSQL_PASSWORD=secret
      ports:
        - "38594:3306"

    webserver:
      image: nginx:alpine
      container_name: stagecompanion-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "38592:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: stagecompanion-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

